### ISSUE TITLE
Rename "Download" button to "Upload"

### ISSUE THREAD

**Issue by WolfgangGitHub** [madmachineio/vscode-madmachine#6]
To be conform with other embedded platforms such as Arduino IDE rename the "Download" button within the extension to "Upload". Upload meaning load the code from my machine 'up' to the connected device.

**Comment by andy0808** [comment]
Thank you for your suggestion. It's indeed a bit confusing, even in the embedded field. Actually, we've given serious thought to what we should call this action. We looked to the most professional and widely used embedded IDEs for guidance: KEIL and IAR. Both use "Download" to describe the action of copying the binary file from the host machine to the microcontroller.

You can see this in the pictures below:

![image](https://github.com/madmachineio/vscode-madmachine/assets/38826545/6d8d9c5c-3c77-4d57-a59c-f6fdf430c221)

![image](https://github.com/madmachineio/vscode-madmachine/assets/38826545/5d8f7bd4-38dd-4de8-a91c-833e324e8eb5)

After comparing the different names used in embedded tools, we decided to follow this approach. But I really appreciate your feedback : )

**Comment by WolfgangGitHub** [comment]
Ah - interesting. I was not aware of the different approaches.
